web/components/swap.tsx
=> Remove appearance of input type number in Firefox

web/components/testnet-modal.tsx
|Before|After|
|---|---|
|![Screen Shot 2021-06-10 at 12 12 41 PM](https://user-images.githubusercontent.com/1909957/121517439-46f4aa80-c9e7-11eb-9f43-cf3ccbd5d1f2.png)|![Screen Shot 2021-06-10 at 12 12 24 PM](https://user-images.githubusercontent.com/1909957/121517436-465c1400-c9e7-11eb-9c00-a2f90c07a41b.png)|
=> Clean up testnet modal UI

web/components/mint.tsx, web/components/stake.tsx, web/components/swap.tsx
Still WIP, will add screenshots when ready.
=> UI improvements for Stake page

web/components/collateral-type-group.tsx, web/components/collateral-type.tsx, web/components/header.tsx, web/components/home.tsx
=> Navigation refactoring

web/components/header.tsx
- Fix misalignment issue for `Governance`
- Add attributes to external links
- Add External Link that indicates for `Docs` and `Security`
=> Navigation fixes

web/common/context.ts, web/components/create-vault-step-one.tsx
I wanted there to be a "max" button, so I used this as an excuse to get the project setup and contribute 🙂
I totally understand if you don't want to merge this, please feel free to just close it if you'd rather take a different approach.
Some of the changes are just from VSCode running ESLint. I had to make some changes to get ESLint to work in my workspace, and I can push those if you're interested.
=> feat: add link to use max balance/mint

web/components/header.tsx
Fixes #39 
For demo purposes I put a 2000px height on the content, check it out:
https://user-images.githubusercontent.com/1909957/122793711-6c20cd00-d2b3-11eb-9e3a-527ea526523b.mov
=> Make navbar sticky

web/common/get-price.ts, web/components/mint.tsx
=> tweak: get the DIKO price from AMM

web/components/collateral-type.tsx, web/components/manage-vault.tsx, web/components/mint.tsx, web/components/smart-contract-balance.tsx, web/components/stake.tsx, web/components/swap.tsx, web/components/vault.tsx
=> fix: fix rounding up of numbers

web/components/create-vault-step-one.tsx, web/components/create-vault-transact.tsx
Fixes several issues:
#29 
#52 
#64
=> fix: fix several front-end vault bugs

clarity/contracts/arkadiko-auction-engine-v1-1.clar
=> fix: fix minimum collateral amount method in auctions

web/components/app.tsx, web/components/create-vault-step-one.tsx, web/components/header.tsx, web/components/input-amount.tsx, web/components/manage-vault.tsx, web/components/stake.tsx
=> Add `Max.` button on input fields where you can enter an amount

web/components/collateral-type-group.tsx, web/components/create-vault-confirm.tsx, web/components/create-vault-step-one.tsx, web/components/input-amount.tsx
=> Vault creation UX/UI improvements

CHANGELOG.md, web/components/app.tsx, web/components/header.tsx, web/components/sub-header.tsx
Fixes #81 and #48
@Macxim I'll let you fix/improve the design ^^
Can also be a sidebar on the bottom or right, no idea what is best.. but I guess top might be most convenient?
=> feat: add sub-header with wallet balance

web/components/swap-settings.tsx, web/components/swap.tsx
=> Add information in tooltips for Swap section

web/components/swap.tsx
https://user-images.githubusercontent.com/1909957/123696176-5c752b80-d853-11eb-971e-c45867efe0dd.mov
This fixes #37
=> Better UX for Swap button

web/components/swap.tsx
Fixes #35 
https://user-images.githubusercontent.com/1909957/123791985-04343d00-d8d8-11eb-9184-12776e210ebe.mov
=> Swap: fixes overflow and broken layout when input is too long

web/components/input-amount.tsx
=> Fix inputs fields where Max button would be pushed out of container

web/components/landing.tsx
The link was pointing the old repo
=> Fix link in landing

web/components/swap.tsx
=> feat:add a single button to add/remove liquidity

web/components/input-amount.tsx
|Before|After|
|---|---|
|<img width="423" alt="Screen Shot 2021-07-02 at 10 00 09 PM" src="https://user-images.githubusercontent.com/1909957/124328123-f2c18e00-db80-11eb-8be9-e5d351092d49.png">|<img width="430" alt="Screen Shot 2021-07-02 at 9 59 21 PM" src="https://user-images.githubusercontent.com/1909957/124328121-f228f780-db80-11eb-9f30-bab03b5a19de.png">|
This should fix #114.
=> Fix input width and clickable area

clarity/contracts/arkadiko-governance-v1-1.clar, clarity/tests/arkadiko-governance-v1-1_test.ts, clarity/tests/arkadiko-stake-pool-diko-usda-v1-1_test.ts, scripts/proposal-change-stacker.js, web/common/proposal-utils.ts, web/components/collateral-type-group.tsx, web/components/create-vault-step-one.tsx, web/components/governance.tsx, web/components/new-vault.tsx, web/components/proposal-group.tsx, web/components/proposal.tsx, web/components/stake.tsx, web/components/view-proposal.tsx
=> feat: UI improvements for Governance and View Proposal

clarity/tests/arkadiko-stake-pool-diko-v1-1_tests.ts
All tests are working again on my side. Please double check.
=> Fix diko pool tests

web/components/token-swap-list.tsx
|Before|After|
|---|---|
|![Screen Shot 2021-07-14 at 10 43 07 AM](https://user-images.githubusercontent.com/1909957/125600929-04b34a53-b80b-4b65-bc42-9803c5e2b1ba.png)|![Screen Shot 2021-07-14 at 10 42 25 AM](https://user-images.githubusercontent.com/1909957/125600935-feb9ea5f-9478-4802-a4cb-89c908ef7c0c.png)|
=> Fix width of switcher so that tokens are all readable

clarity/contracts/arkadiko-freddie-v1-1.clar, clarity/tests/arkadiko-freddie-v1-1_test.ts, clarity/tests/models/arkadiko-tests-vaults.ts, web/components/manage-vault.tsx
- A user can pay back all debt when they want (vault not auto closed)
- A user can close a vault that has no debt left (and is not stacking STX)
- When closing a vault with debt, it will be paid back automatically
=> User can now pay back all debt while stacking

clarity/contracts/arkadiko-dao.clar
@nieldeckx does this fix https://github.com/arkadiko-dao/arkadiko/issues/142 as well?
=> fix: allow minting of DIKO by wSTX-DIKO stake pool

web/components/app.tsx, web/package.json, yarn.lock
=> tweak: scroll to top when navigating

scripts/utils.js, web/components/manage-vault.tsx
=> tweak: redirect to vaults page after closing vault

clarity/contracts/arkadiko-freddie-v1-1.clar
Fixes #38 
There's two options:
1. This approach
2. Remove the paying of stability fee in the mint method
=> tweak: pay stability fee on minting USDA if enough balance

web/components/stake.tsx
APY is now calculated for each pool.
=> fix: calculate staking APYs based on each staking pool

docs/setup.md
Location of toml files has moved.
=> Location of toml files has moved.

docs/setup.md
Adds additional steps to getting mocknet working
=> Adds additional steps to getting mocknet working

web/components/add-swap-liquidity.tsx, web/components/auction-group.tsx, web/components/auctions.tsx, web/components/create-vault-transact.tsx, web/components/lot.tsx, web/components/manage-vault.tsx, web/components/mint.tsx, web/components/remove-swap-liquidity.tsx, web/components/stake-diko-modal.tsx, web/components/stake-lp-modal.tsx, web/components/stake.tsx, web/components/swap.tsx, web/components/unstake-diko-modal.tsx, web/components/unstake-lp-modal.tsx, web/components/vault.tsx, web/components/view-proposal.tsx
Straightforward changes. I think all transactions we broadcast are eligible for either a microblock of an anchor block.
See more info
https://docs.stacks.co/understand-stacks/microblocks
https://docs.stacks.co/understand-stacks/transactions#anchor-mode
=> feat: integrate microblocks anchor mode

web/components/manage-vault.tsx, web/components/mint.tsx
=> Add Unclaimed Rewards to Vaults Overview

clarity/contracts/arkadiko-stake-registry-v1-1.clar, clarity/tests/arkadiko-stake-pool-diko-usda-v1-1_test.ts
=> Update pool rewards

web/components/mint.tsx
The button allow to execute a contract call that won't do anything.
=> Disable Claim rewards when non pending rewards

web/components/add-swap-liquidity.tsx, web/components/pool-position.tsx, web/components/pool.tsx, web/components/remove-swap-liquidity.tsx, web/components/routes.tsx, web/components/swap.tsx, web/components/token-swap-list.tsx
<p align="center"><img align="center" width="593" alt="Screen Shot 2021-08-23 at 5 18 04 PM" src="https://user-images.githubusercontent.com/1909957/130481988-90fcfa70-92ba-4c65-86dd-092c01825be1.png"></p>
Logic still needs to be added though 😅
=> feat: add Pool page and liquidity positions

clarity/contracts/arkadiko-dao.clar, clarity/contracts/arkadiko-diko-init.clar, clarity/contracts/arkadiko-freddie-v1-1.clar, clarity/contracts/arkadiko-governance-v1-1.clar, clarity/contracts/arkadiko-liquidator-v1-1.clar, clarity/contracts/arkadiko-stacker-payer-v1-1.clar, clarity/contracts/arkadiko-stake-registry-v1-1.clar
This will allow us to set off-chain observers to build analytics if/when needed.
=> tweak: add print statements for logging and analytics

clarity/contracts/arkadiko-freddie-v1-1.clar
See https://github.com/0f/0f-ark-2108/issues/6
=> fix: possible total debt versus maximum debt discrepancy [0f-ARK-005]

web/components/unstake-diko-modal.tsx
@Macxim fix for the bug you discovered
=> fix: unstake DIKO popup shows wrong max amount

clarity/contracts/arkadiko-auction-engine-v1-1.clar, clarity/contracts/arkadiko-freddie-v1-1.clar, clarity/contracts/arkadiko-sip10-reserve-v1-1.clar
see issue https://github.com/0f/0f-ark-2108/issues/8
=> fix: defective funds migration on contract upgrade [0f-ARK-007]

clarity/contracts/arkadiko-stake-pool-wstx-diko-v1-1.clar, clarity/contracts/arkadiko-stake-pool-wstx-usda-v1-1.clar, clarity/contracts/tests/arkadiko-stake-pool-diko-usda-tv1-1.clar, clarity/tests/arkadiko-stake-pool-wstx-diko-v1-1_test.ts, clarity/tests/arkadiko-stake-pool-wstx-usda-v1-1_test.ts, clarity/tests/models/arkadiko-tests-stake.ts, clarity/tests/models/arkadiko-tests-tokens.ts
See https://github.com/0f/0f-ark-2108/issues/7
=> fix: LP tokens wSTX-DIKO and wSTX-USDA being staked by users are lost [0F-ARK-006]

clarity/contracts/arkadiko-collateral-types-v1-1.clar, clarity/tests/arkadiko-collateral-types-v1-1_test.ts, clarity/tests/arkadiko-freddie-v1-1_test.ts, clarity/tests/models/arkadiko-tests-collateral-types.ts, clarity/tests/models/arkadiko-tests-vaults.ts
=> test: add tests for collateral type

web/components/manage-vault.tsx
=> fix: parse amount to burn as integer

web/components/governance.tsx
=> tweak: nicer placeholder for proposal

web/components/view-proposal.tsx
https://user-images.githubusercontent.com/1909957/139559573-8b7d9d3b-3447-41ac-a3fb-91120a0ff2b9.mov
=> tweak: add nicer placeholders for proposal details

web/components/banner.tsx
|Before|After|
|---|---|
|![Screen Shot 2021-11-05 at 9 48 50 AM](https://user-images.githubusercontent.com/1909957/140491710-3db4e93f-a927-416e-8296-5d50a82faec2.png)|![Screen Shot 2021-11-05 at 9 48 57 AM](https://user-images.githubusercontent.com/1909957/140491717-e1cf3c3d-3199-41f3-9519-0597256ccfb2.png)|
=> fix: banner not showing correctly on smaller viewport

web/components/app.tsx, web/components/footer.tsx
Add simple footer with link to Analytics and Coming Soon badge.
👀
=> feat: add footer

web/components/view-proposal.tsx
Necessary to let users claim their tokens again
=> feat: add buttons on governance proposal to claim back tokens you used in a gov vote

web/components/add-swap-liquidity.tsx, web/components/create-vault-transact.tsx, web/components/pool-position.tsx, web/components/pool.tsx, web/components/remove-swap-liquidity.tsx, web/components/stake-lp-row.tsx, web/components/stake.tsx, web/components/swap-loading-placeholder.tsx, web/components/swap-settings.tsx, web/components/swap.tsx, web/components/unstake-lp-modal.tsx
Closes #313 and #291
- keep tabs clickable while loading, rework placeholder
- fix slippage tolerance Auto button conditional classes 
- improve loading states for add liquidity
- improve loading state for pool position 
- add loading states for remove liquidity
=> tweak: swap and pool improvements

web/components/view-proposal.tsx
=> Show amount of tokens that can be claimed after proposal ends

web/components/proposal-group.tsx, web/components/view-proposal.tsx
|Before|After|
|---|---|
|![Screen Shot 2021-11-12 at 11 16 38 AM](https://user-images.githubusercontent.com/1909957/141459666-3b108a92-d5e9-47e4-ac8b-e7a5a40ab240.png)|![Screen Shot 2021-11-12 at 11 09 40 AM](https://user-images.githubusercontent.com/1909957/141459671-594f9023-1b85-48cd-b546-603c12298cbc.png)|
=> tweak: update proposal UI in Governance

web/common/vault-utils.ts, web/components/stake.tsx
> ✖ 197 problems (197 errors, 0 warnings)
>  2 errors and 0 warnings potentially fixable with the `--fix` option.
> ✖ 158 problems (158 errors, 0 warnings)
=> tweak: fix lint/TypeScript errors

web/components/stake.tsx
=> fix stake value

web/components/auction-group.tsx, web/components/stake-diko-modal.tsx, web/components/stake-lp-modal.tsx, web/components/stake.tsx, web/components/ui/modal.tsx, web/components/unstake-diko-modal.tsx, web/components/unstake-lp-modal.tsx
https://user-images.githubusercontent.com/1909957/141855908-575e95be-3ba6-4570-be9d-4a551efe0718.mov
=> fix: closing/action function on modal component

web/components/manage-vault.tsx
Closes #344 
Feel free to update copy.
Do we need to display the alert conditionally?
=> tweak: add info when adding extra collateral

web/components/stake.tsx
fix for https://github.com/arkadiko-dao/arkadiko/issues/349
=> fix for when state balance is undefined

web/components/stake-diko-modal.tsx, web/components/stake-lp-modal.tsx, web/components/ui/modal.tsx, web/components/unstake-diko-modal.tsx, web/components/unstake-lp-modal.tsx
Closes #306 
https://user-images.githubusercontent.com/1909957/142074794-05b2239e-b3a9-42bd-87bf-78bafe01d77a.mov
=> Disable main button in staking/unstaking modals if input value > balance

web/common/transactions.ts
Fix for: https://github.com/arkadiko-dao/arkadiko/issues/299
=> fix: fetch all mempool pages to find pending transactions for a user

web/components/app.tsx
Fix for: https://github.com/arkadiko-dao/arkadiko/issues/259
=> fix: make sure stacking days left is always positive

web/components/balances.tsx, web/components/smart-contract-balance.tsx
https://github.com/arkadiko-dao/arkadiko/issues/255
=> feat: show stDiko and LP tokens on balance page

web/common/get-price.ts, web/components/mint.tsx
https://github.com/arkadiko-dao/arkadiko/issues/308
=> feat: show when oracle was updated

web/common/transactions.ts, web/common/vault-utils.ts, web/components/manage-vault.tsx, web/components/proposal-group.tsx, web/components/stake.tsx, web/components/swap.tsx, web/components/view-proposal.tsx, web/scripts/deploy-contracts.ts
|Before|After|
|---|---|
|<img width="1304" alt="Screen Shot 2021-11-19 at 11 14 47 PM" src="https://user-images.githubusercontent.com/1909957/142702822-a5ac2378-49ab-4ef7-a1b2-c675768a0c2f.png">|<img width="1304" alt="Screen Shot 2021-11-19 at 11 13 42 PM" src="https://user-images.githubusercontent.com/1909957/142702830-28bbb083-4cdd-4ae1-999e-fa17e74141a9.png">|
|<img width="1303" alt="Screen Shot 2021-11-19 at 11 14 39 PM" src="https://user-images.githubusercontent.com/1909957/142702825-ad3da104-6ddd-4efe-a089-2df64f14b5cb.png">|<img width="1288" alt="Screen Shot 2021-11-19 at 11 14 06 PM" src="https://user-images.githubusercontent.com/1909957/142702828-7ab94a7a-e7a8-489b-9063-f0f4fe2dc7a7.png">|
=> fix: sort Governance proposals and fix issue with vote percentages

web/components/stake.tsx
https://user-images.githubusercontent.com/1909957/142838191-238e456c-f92e-4862-8790-7bf3ff267cd1.mov
=> tweak: change three-dot menu to Actions for better consistency

web/components/proposal.tsx
=> tweak: add proposal number in proposal list

web/components/swap.tsx
https://github.com/arkadiko-dao/arkadiko/issues/377
=> feat: switch exchange rate

web/components/collateral-type.tsx, web/components/create-vault-step-one.tsx, web/components/governance.tsx, web/components/header.tsx, web/components/mint.tsx, web/components/proposal-group.tsx, web/components/stake-lp-row.tsx, web/components/stake.tsx, web/components/swap.tsx, web/components/ui/placeholder.tsx, web/components/vault-group.tsx, web/components/vault.tsx
As seen on Discord, some people are able to connect their wallet on mobile.
This PR fixes a few things on mobile and rework a few others:
- change vaults display on mobile
- allow mobile menu to close on click on menu items
=> tweak: fixes for mobile

web/components/stake.tsx, web/components/unstake-diko-modal.tsx
=> fix: Add DIKO column and update modal with DIKO amount

analytics-web/components/balances.tsx, analytics-web/components/home.tsx, analytics-web/components/smart-contract-balance.tsx
|Before|After|
|---|---|
|![Screen Shot 2021-11-30 at 9 17 12 AM](https://user-images.githubusercontent.com/1909957/144019336-436ef63f-d4f9-4b5e-9218-872b77556980.png)|![Screen Shot 2021-11-30 at 10 19 50 AM](https://user-images.githubusercontent.com/1909957/144029250-e8611f50-6d27-4cef-88c5-797c66652bbd.png)|
=> tweak: update cards for balances contracts

analytics-web/components/prices.tsx, analytics-web/tailwind.config.js
=> fix: components path in tailwind config for analytics folder

web/components/stake.tsx
We calculated the APR with the nominator as DIKO emissions for a pool (correct) but the denominator as LP tokens, which is wrong.
I now calculate the value of the LP tokens in amount of DIKO, so the division is "DIKO emissions of that pool" / "value of all staked LP tokens denominated in DIKO".
=> fix: add correct APRs for LP pools

web/components/mint.tsx
=> tweak: remove vault rewards

web/components/collateral-type.tsx, web/components/manage-vault.tsx, web/components/pool-position.tsx, web/components/pool.tsx, web/components/swap.tsx, web/components/ui/alert.tsx
- dark mode fixes for collateral types
- responsive fixes
- go to correct location when selecting option in select (on mobile)
=> fix: dark mode issues and <select> Swap/Pool on mobile

web/components/view-proposal.tsx
Actual changes are just on lines: 674, 682, 715 and 723.
The rest is just prettier linting, sorry for the inconvenience.
=> fix: governance proposal winner badge color

web/components/collateral-type.tsx, web/components/header.tsx, web/components/mint.tsx, web/components/prices.tsx, web/components/swap-settings.tsx
Also some minor dark mode fixes.
=> tweak: Extract prices to its own component and fix responsive

web/package.json, yarn.lock
Should fix this issue https://github.com/hirosystems/stacks-wallet-web/issues/2166
=> deps: upgrade @stacks/auth dependency

web/components/prices.tsx, web/components/tx-sidebar.tsx
|Before|After|
|---|---|
|<img width="360" alt="Screen Shot 2022-01-29 at 8 23 43 PM" src="https://user-images.githubusercontent.com/1909957/151676430-23050587-d4e3-4198-b42b-c4daeb45f69b.png">|<img width="362" alt="Screen Shot 2022-01-29 at 8 23 31 PM" src="https://user-images.githubusercontent.com/1909957/151676432-0d5406ac-2621-45d6-ba7d-a0ad82a8715f.png">|
=> fix: network switcher selected/active props

web/components/governance.tsx, web/components/proposal.tsx
Not very beautiful code-wise 😞 but UI looks better and less confusing.
=> tweak: separate governance v1 from current proposals

analytics-web/components/market-cap.tsx, analytics-web/components/prices.tsx
=> refactoring: prices and market cap

analytics-web/components/tvl.tsx
|Before|After|
|---|---|
|<img width="1161" alt="Screen Shot 2022-02-07 at 10 28 16 PM" src="https://user-images.githubusercontent.com/1909957/152882964-3af8f841-82b8-4bf9-afa2-ec35ac3cfbb7.png">|<img width="1160" alt="Screen Shot 2022-02-07 at 10 27 55 PM" src="https://user-images.githubusercontent.com/1909957/152882959-14e052e8-4f89-4ea3-88d6-aa0550b06c5a.png">|
Feel free to update tooltips copy ^^
=> refactoring: rework TVL in analytics

web/common/get-price.ts
`getPriceInfo` and `getPrice` are very similar.
Small refactoring to avoid repetition.
=> refactoring: getPrice function

web/components/manage-vault.tsx
Reported here: https://discord.com/channels/827123370520215562/854718089076932660/948967991784128623
=> fix: display vault status and alert only if debt > 0

scripts/add-stake-lp-rewards-to-dao.js, scripts/set-pool-data-xbtc.js, scripts/set-pool-data.js, web/components/stake-lp-modal.tsx, web/components/stake-lp-row.tsx, web/components/stake.tsx
This PR does a few things:
- Calculate APR according to new emissions
- Add scripts to update emissions on stake registry
=> tweak: update new emissions

web/components/liquidations-reward.tsx, web/components/liquidations.tsx
=> feat: bulk claim liquidation rewards

web/components/liquidations.tsx
|Before|After|
|---|---|
|![Screen Shot 2022-04-29 at 8 12 27 AM](https://user-images.githubusercontent.com/1909957/165899766-2ff478f1-53eb-4daf-91c5-0ddff0ea41dd.png)|![Screen Shot 2022-04-29 at 8 11 33 AM](https://user-images.githubusercontent.com/1909957/165899707-83ef0445-da00-4717-84f3-53e9b0673625.png)|
=> Fix copy in Liquidation fund

web/components/header.tsx
=> Add pill to header Governance item when a vote is in progress

web/components/auctions.tsx, web/components/header.tsx, web/components/routes.tsx
- auctions => liquidations (also change route path)
- vaults => borrow (didn't change route path)
=> tweak: rename sections

web/components/liquidations.tsx
=> feat: button to load liquidation rewards

web/components/liquidations.tsx
=> fix: duplicate reward IDs

web/components/header.tsx
https://discord.com/channels/827123370520215562/854812753058332693/1009789695628169276
=> feat: add pending txs indicator next to address

web/components/manage-vault.tsx
=> feat: cleanup and add stability fee to vault details

api/app/controllers/pairs_controller.rb, api/config/routes.rb
According to documentation here 
https://docs.google.com/document/d/1v27QFoQq1SKT3Priq3aqPgB70Xd_PnDzbOCiuoCyixw/edit
=> feat: add /pairs endpoint to API

api/app/controllers/tickers_controller.rb, api/app/models/pool.rb
According to CoinGecko docs: https://docs.google.com/document/d/1v27QFoQq1SKT3Priq3aqPgB70Xd_PnDzbOCiuoCyixw/edit
=> feat: add tickers API endpoint

analytics-web/common/utils.ts, analytics-web/components/smart-contract-balance.tsx, api/app/models/blockchain.rb, api/app/models/pox_calculator.rb, scripts/utils.js, shared/utils.ts, web/common/utils.ts, web/common/websocket-tx-updater.ts, web/components/contract-transaction.tsx, web/components/explorer-link.tsx, web/components/tx-sidebar.tsx, web/components/view-proposal.tsx
See https://forum.stacks.org/t/domain-migrations-for-hiro-hosted-services/14609
=> chore: update API urls to Hiro

web/components/stake-diko-section.tsx, web/components/stake-lp-row.tsx, web/components/stake-usda-section.tsx, web/components/stake.tsx
|Before|After|
|---|---|
|<img width="447" alt="Screenshot 2023-04-17 at 10 36 17 PM" src="https://user-images.githubusercontent.com/1909957/232616361-d5a8f1f6-dffd-4461-803f-c8f6af5c7fce.png">|<img width="450" alt="Screenshot 2023-04-17 at 10 36 44 PM" src="https://user-images.githubusercontent.com/1909957/232616365-f33b858f-07e3-4cae-82ef-1a6410ba4ec8.png">|
=> fix: LP staking refactoring due to overflowing menu on mobile

web/components/manage-vault.tsx, web/components/stake-lp-row.tsx
=> fix: UI adjustments for Manage and Stake page

web/components/governance.tsx
=> feat: add additional note in governance

web/components/add-swap-liquidity.tsx, web/components/remove-swap-liquidity.tsx, web/components/swap.tsx
This should fix #593 
Preview:
=> feat: improve UX/UI for mobile

web/components/collateral-card.tsx
Feel free to change copy or anything.
=> feat: add DIKO rewards info for sBTC vaults

.github/workflows/ci-clarinet.yml, clarity/Clarinet.toml, clarity/contracts/arkadiko-dao.clar, clarity/contracts/vaults-v2/arkadiko-vaults-operations-v1-2.clar, clarity/contracts/vaults-v2/arkadiko-vaults-operations-v1-3.clar, clarity/contracts/wstx-token.clar, clarity/deployments/default.devnet-plan.yaml, clarity/tests/arkadiko-vaults-operations-v1-1_test.ts, clarity/tests/models/arkadiko-tests-vaults-operations.ts, clarity/tests/wstx-token_test.ts, scripts/governance-update-vaults-operations.js, scripts/v2/wstx-set-protocol-addresses.js, scripts/vaults-close.js, scripts/vaults-create.js, scripts/vaults-update.js, web/common/vault-utils.ts, web/components/create-vault-transact.tsx, web/components/manage-vault.tsx, web/components/vault-burn.tsx, web/components/vault-deposit.tsx, web/components/vault-mint.tsx, web/components/vault-withdraw.tsx, web/scripts/deploy-contracts-v2.ts
NOTE:
- We need to add the new operations contract to the **wstx-token**
- Update immunefi
=> fix: collateral to debt ratio calculation
