- clarity/contracts/arkadiko-auction-engine-trait-v1.clar
- clarity/contracts/arkadiko-auction-engine-v1-1.clar
- clarity/tests/models/arkadiko-tests-vaults.ts
- web/components/auction.tsx
This fixes the read-only issue we had when passing a trait as a parameter. The function would always be marked as a write function within the Stacks blockchain.
@nieldeckx Now we can tackle https://trello.com/c/Jnh3V5EX/67-clear-out-all-static-contract-call-invocations-for-which-a-trait-exists - I might do that in the coming week before testnet still.
> tweak: improve read-only collateral function in auction engine with traits

- clarity/tests/arkadiko-auction-engine-v1-1_test.ts
- clarity/tests/arkadiko-diko-guardian-v1-1_test.ts
- clarity/tests/arkadiko-diko-init_test.ts
- clarity/tests/arkadiko-freddie-v1-1_test.ts
- clarity/tests/arkadiko-governance-v1-1_test.ts
- clarity/tests/arkadiko-liquidator-v1-1_test.ts
- clarity/tests/arkadiko-sip10-reserve-v1-1_test.ts
- clarity/tests/arkadiko-stacker-v1-1_test.ts
- clarity/tests/arkadiko-stake-registry-v1-1_test.ts
- clarity/tests/arkadiko-swap-v1-1_test.ts
- clarity/tests/arkadiko-vault-rewards-v1-1_test.ts
- clarity/tests/models/arkadiko-tests-swap.ts
- clarity/tests/models/arkadiko-tests-tokens.ts
- clarity/tests/models/arkadiko-tests-vaults.ts
- clarity/tests/xusd-token_test.ts
There was an issue in the way the `expectUint` was written, that was fixed with clarinet v0.13.0.
The following behavior would have been observed in prior versions:
```
"u100".expectUint(1); // pass
"u100".expectUint(10); // pass
"u100".expectUint(100); // pass
"u100".expectUint(1000); // fail
```
This PR is updating the version being imported, and fixing the broken expectations (which looks like broken tests to me, vs broken contracts).
> Chore: update clarinet 0.13.0

- web/components/add-swap-liquidity.tsx
- web/components/auction-group.tsx
- web/components/auctions.tsx
- web/components/create-vault-transact.tsx
- web/components/lot.tsx
- web/components/manage-vault.tsx
- web/components/mint.tsx
- web/components/remove-swap-liquidity.tsx
- web/components/stake.tsx
- web/components/swap.tsx
- web/components/vault.tsx
- web/components/view-proposal.tsx
Fixes a small bug where you can have multiple accounts on one wallet and sometimes it wouldn't pick the correct address to sign.
> fix: add stxAddress to all contract calls to sign from the correct address

- clarity/contracts/arkadiko-stake-pool-diko-v1-1.clar
- clarity/tests/arkadiko-stake-pool-diko-v1-1_tests.ts
- web/components/stake.tsx
@nieldeckx I think you implemented this for the user, but that is not in line with how the other pool contracts calculate the `get-total-staked` amount? Also it crashes in the front-end now..
Can you elaborate if this is correct or not?
> fix: calculate get-total-staked as total amount staked, not just for user

- clarity/contracts/arkadiko-auction-engine-v1-1.clar
- clarity/contracts/arkadiko-dao.clar
When bad debt had to be covered and STX collateral was not sufficient, we would previously take this from the foundation reserve.
That resulted in a systemic risk where tokens from the foundation could be drained. This is now changed and we mint new DIKO tokens.
> fix: mint new DIKO when bad debt needs to be covered by a debt auction

- clarity/Clarinet.toml
- clarity/contracts/arkadiko-stake-pool-diko-slash-v1-1.clar
- clarity/contracts/arkadiko-stake-pool-diko-v1-1.clar
- clarity/tests/arkadiko-stake-pool-diko-slash-v1-1_test.ts
Added a new contract which can be deployed through governance. Once active in the DAO, anyone can execute the slash once to transfer X% (30% in this example contract) of DIKO pool funds to the foundation.
> DIKO pool slashing

- clarity/Clarinet.toml
- clarity/contracts/arkadiko-governance-v1-1.clar
- clarity/contracts/arkadiko-stake-pool-diko-trait-v1.clar
- clarity/contracts/arkadiko-stake-pool-diko-v1-1.clar
- clarity/contracts/arkadiko-stake-pool-trait-v1.clar
- clarity/tests/arkadiko-governance-v1-1_test.ts
- clarity/tests/arkadiko-stake-pool-diko-slash-v1-1_test.ts
- clarity/tests/arkadiko-stake-pool-diko-usda-v1-1_test.ts
- clarity/tests/arkadiko-stake-pool-diko-v1-1_tests.ts
User was not able to vote with stDIKO. This is fixed.
Users are able to vote with both DIKO and stDIKO. However 1 DIKO is not equal to 1 stDIKO so we need to take this into account when counting votes. Improved voting by converting stDIKO to DIKO at the current rate defined in the stake pool.
> Fixed voting with stDIKO

- web/components/app.tsx
We need the `theme` and `ThemeProvider` from `@blockstack/ui` for the tooltips to be displayed properly.
I shouldn't have removed them in #173.
I will probably refactor this later anyway in favor of https://atomiks.github.io/tippyjs/
> Fix tooltips

- web/components/manage-vault.tsx
It was pointing to an incorrect function and missing its own function.
> Fix Withdraw Max amount Input

- web/components/create-vault-confirm.tsx
The checked/unchecked status was not correctly being stored in the state and in consequence not being passed to the transaction.
> Fix: Autostack not being reflected in transaction

- web/components/add-swap-liquidity.tsx
- web/components/pool.tsx
- web/components/remove-swap-liquidity.tsx
|Before|After|
|---|---|
|![Screen Shot 2021-09-16 at 6 36 19 AM](https://user-images.githubusercontent.com/1909957/133559632-ac5d2ffb-9f43-4261-b896-686bc61733ad.png)|![Screen Shot 2021-09-16 at 6 36 38 AM](https://user-images.githubusercontent.com/1909957/133559630-1fc37849-f465-4438-ba51-412be1f9062e.png)|
> Pool small UX improvements

- web/components/manage-vault.tsx
The reason the burn PC was failing was due to the extra payment of stability fees in the burn method. As a result, the PC showed a USDA fee that is too low.
> fix: add some margin to burn post condition for paying stability fee

- clarity/tests/arkadiko-stacker-v1-1_test.ts
- clarity/tests/models/arkadiko-tests-stacker.ts
Stacker tests suddenly failed. Error: (define-constant ERR_STACKING_THRESHOLD_NOT_MET 11)
See: https://explorer.stacks.co/txid/0x41356e380d164c5233dd9388799a5508aae929ee1a7e6ea0c18f5359ce7b8c33?chain=mainnet
The method "get-stacking-minimum" on the pox contract returns u2083333333333. So a minimum of 2,083,333 STX is needed to initiate stacking. Updated the tests to reach this minimum when stacking.
> fix: stacker tests failing

- clarity/contracts/arkadiko-vault-data-v1-1.clar
- clarity/tests/arkadiko-vault-rewards-v1-1_test.ts
- clarity/tests/models/arkadiko-tests-vaults.ts
Changed:
- vault-entries: 500 -> 20
Others:
- winning-lots: 100
- auction-ids: 1500
- pairs-list: 2000
- stacking-payout-lots: 500
- proposal-ids: 100
- contract-changes: 10
I think they are fine for now. We will need to find a way to have more auctions and proposals but this would require too much refactoring at this point.
> Improve list limits [0f-ARK-010]

- clarity/contracts/arkadiko-freddie-v1-1.clar
I saw your comment in the audit ticket. If a user creates a vault with wallet A and wants to deposit funds from wallet B, he can just transfer the funds first. All platforms I have been using work like this. Transfers on Stacks are easy and cheap.
A check on SC is better imo as now you can trust the SC instead of a centralised FE.
> Users can deposit into any vault [0f-ARK-004]

- clarity/contracts/arkadiko-collateral-types-v1-1.clar
- clarity/tests/arkadiko-collateral-types-v1-1_test.ts
- clarity/tests/models/arkadiko-tests-collateral-types.ts
We can already change the risk parameters in the first version at launch.
This will help us change the contract address (i.e. for xBTC if we need to change it for some reason)
> feat: allow changing token address of collateral type

- clarity/contracts/arkadiko-stake-pool-diko-v1-1.clar
- clarity/contracts/tests/arkadiko-stake-pool-diko-tv1-1.clar
- web/components/balances.tsx
- web/components/smart-contract-balance.tsx
Feel free to adjust copy.
Also, it would be nice to have a `—` when data is not applicable. For example: 
I managed to do it for STX Balance but not for the rest of them.
> tweak: update balances table with more info

- web/components/swap.tsx
This is a fix for #340 
Not sure if it's the right one, but it fixes the issue.
> fix: show token Y amount as text in swap

- web/components/vault.tsx
Fixes #312 - numbers were not parsed well.
> fix: do not show red bg if collateralisation is healthy

- web/components/auction-group.tsx
- web/components/input-amount.tsx
- web/components/stake-diko-modal.tsx
- web/components/stake-lp-modal.tsx
- web/components/stake.tsx
- web/components/ui/modal.tsx
- web/components/unstake-diko-modal.tsx
- web/components/unstake-lp-modal.tsx
- web/components/view-proposal.tsx
Remove the modal import from `@blockstack/ui` and use our own modal component from `Headless UI` (https://headlessui.dev/react/dialog).
There are still 6 occurrences of the previous modal. We can replace them in another PR.
- 2 in `view-proposal.tsx`: still not sure how to handle the UI since they have 3 buttons instead of 2, I'll give it some thought;
- 4 in `manage-vault.tsx`: IMO, they should be extracted to their own component like we did for `stake-diko`, `unstake-diko`, `stake-lp`, `unstake-lp` modals.
> feat: add Modal component

- web/components/stake-lp-modal.tsx
- web/components/stake-lp-row.tsx
- web/components/stake.tsx
When actions aren't available, give some information as to why.
Again, feel free to update copy if you don't like it.
> tweak: display all actions in stake DIKO dropdown

- web/components/liquidations.tsx
- web/components/stake-lp-row.tsx
- web/components/ui/modal.tsx
I disabled the button if there are no redeemable STX to prevent useless transactions.
> Small UX/UI improvements for Liquidations

- web/components/liquidations.tsx
Small fix to always show xSTX redeem box, as people on Discord where confused about where to redeem xSTX..
> fix: show xSTX redeem box when no xSTX in wallet

- web/components/collateral-card.tsx
- web/tailwind.config.js
Apparently Tailwind's JIT engine doesn't see concatenated classes.
> fix: Remove concatenated classes for Collateral cards in Borrow section

- web/components/balances.tsx
- web/components/sub-header.tsx
Before that, balances on mobile were just hidden.
https://user-images.githubusercontent.com/1909957/227571956-3a25d1cd-5587-4480-99a0-d4a5993773d2.mov
> feat: display balances on smaller resolutions
